name: hello world
author: phil
description: "greet someone and record the time"
inputs:
  who_to_greet:
    description: "who to greet"
    # required: true
    default: "world"
outputs:
  time:
    description: the time of the greeting
# this is saying that we are gonna use node as our runner
runs:
  using: "docker"
  image: "Dockerfile"

  #entrypoint:
  args:
    # echo you are passing this argument to this in the entrypoint file "INPUT_WHO_TO_GREET: $INPUT_WHO_TO_GREET"

    - ${{ inputs.who_to_greet }}
  env:
    HELLO: WORLD
  post-entrypoint: "/cleanup.sh"
  post-if: runner.os = 'linux'
