name: first workflow name
on: [push]
jobs: 
  run-shell-commands: 
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: multi line command
        run: |
          node -v 
          npm -v 