name: expression and contexts
on: [issues]
run-name: "Expressions & contexts by @${{ github.actor }}, event: ${{ github.event_name}}"
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print working directory
        run: pwd
