name: Simple Action
on: [push]

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Simple js action
        id: greet
        uses: ./.github/actions/hello
        with:
          who_to_greet: Phil
      - name: log greeting time
        run: echo "${{ steps.greet.output.time }}"
      - name: Log ENV Var
        run: echo $HELLO_TIME
