name: Status check functions
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Runs on Failure
        if: Failure()
        run: echo 'Runs only on failure'
      - name: Runs of success
        # you don't actually need to have an if to run success(), becuase success is the default behavior
        if: success()
        run: echo 'Runs on success'
      - name: Always runs
        if: always()
        run: echo 'Always runs'
    #   - name: runs
    #     if: cancelled()
    #     runs: echo 'runs on cancelled'

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    # so this will run as long as failure is true, and job-2 depends on job one, so
    #  failure needs to happen on job one for this to fire
    if: failure()
    steps:
      - run: echo 'job 2'
