name: calling reusuable workflow
on:
  workflow_dispatch:
    # we are taking this input, and passing it to our reusable workflow
    inputs:
      name:
        description: "input description"
        type: string
        default: "phil"
        required: false

jobs:
  # this is how we call to a different repo
  calling-a-reusable-wf:
    uses: github-actions-course/worfklows/.github/worfklows/reusable.yml@main
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
